# Generated by Django 6.0.4 on 2026-04-25 04:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('personal_car', 'Personal Car'), ('taxi', 'Taxi'), ('truck', 'Truck'), ('coaster', 'Coaster'), ('boda_boda', 'Boda-boda')], max_length=20)),
                ('plate_number', models.CharField(max_length=10)),
                ('model_color', models.CharField(help_text='e.g. Toyota Harrier, Silver', max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('nin', models.CharField(blank=True, help_text='Required for Boda-boda only', max_length=20)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_signed_out', models.BooleanField(default=False)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(max_length=15)),
                ('receiver_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('receiver_nin', models.CharField(max_length=20)),
                ('sign_out_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('fee_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_category', models.CharField(max_length=10)),
                ('receipt_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking.vehicle')),
            ],
        ),
    ]
